# Generated by Django 4.2.3 on 2023-07-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Tallas',
            new_name='Talla',
        ),
    ]
