# Generated by Django 4.2.3 on 2023-07-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0004_producto_foto_primcipal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Foto_Primcipal',
            new_name='Foto_Principal',
        ),
    ]
