# Generated by Django 4.2.3 on 2023-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0005_rename_foto_primcipal_producto_foto_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
