# Generated by Django 4.2.3 on 2023-07-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0006_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
