# Generated by Django 4.2.3 on 2023-07-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0007_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ropa.genero'),
            preserve_default=False,
        ),
    ]
