# Generated by Django 4.2.3 on 2023-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0008_producto_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
