# Generated by Django 4.2.3 on 2023-07-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_multimedia_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedade',
            name='titulo_en_admin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
