# Generated by Django 4.2.3 on 2023-07-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_novedade_titulo_en_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
    ]
