# Generated by Django 4.2.3 on 2023-07-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0007_categoria_imagen'),
        ('home', '0004_remove_categoria_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='categoria',
        ),
        migrations.AddField(
            model_name='seccion',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ropa.genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccion',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ropa.producto'),
            preserve_default=False,
        ),
    ]
